In [ ]:
from urllib.request import urlretrieve
import zipfile
import pandas as pd

url = "https://archive.ics.uci.edu/static/public/320/student+performance.zip"
urlretrieve(url, "student_performance.zip")

('student_performance.zip', <http.client.HTTPMessage at 0x7946a2e42000>)

In [ ]:
with zipfile.ZipFile("student_performance.zip", "r") as z:
    z.extractall("student_performance")
# 3. inner ZIP  =>>>> student.zip
inner_zip = "student_performance/student.zip"
with zipfile.ZipFile(inner_zip, "r") as z:
    z.extractall("student_performance/files")

In [ ]:
#read file
df_por = pd.read_csv(
    "student_performance/files/student-por.csv",
    sep=";",      # مهم!
)

In [ ]:
df_por.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [ ]:
df_mat = pd.read_csv(
    "student_performance/files/student-mat.csv",
    sep=";",
)
df_mat.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10